services:
  sitmun-backend:
    build:
      context: ../../back/backend/sitmun-backend-core
      dockerfile: docker/Dockerfile
    container_name: sitmun-backend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/dashboard/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - sitmun-network-oracle
    restart: unless-stopped
    volumes:
      - ../development/backend:/app/config:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle:1521/sitmun3
      SPRING_DATASOURCE_USERNAME: sitmun3
      SPRING_DATASOURCE_PASSWORD: sitmun3
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.OracleDialect
      SPRING_LIQUIBASE_CHANGE_LOG: file:/app/config/liquibase/master.xml
      SPRING_LIQUIBASE_CONTEXTS: dev
      SITMUN_BACKEND_URL: http://localhost:8080/
    depends_on:
      oracle:
        condition: service_healthy
        required: true

  oracle:
    image: gvenzl/oracle-free:23-slim
    restart: unless-stopped
    networks:
      - sitmun-network-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password
      APP_USER: sitmun3
      APP_USER_PASSWORD: sitmun3
      ORACLE_DATABASE: sitmun3
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sitmun3/sitmun3@//localhost:1521/sitmun3", "-c", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 30s
      start_period: 60s
      retries: 3

networks:
  sitmun-network-oracle:
    driver: bridge
